import { config } from "dotenv";
config({ path: ".env.local" });
import { eq } from "drizzle-orm";
import { db } from "../db/client";
import { invoices, payments } from "../db/schema/billing";

async function verifyP41() {
  console.log("Verifying Phase 4.1: Billing Rules and Ledger Schema...");

  const existingOwnerId = "f2d36e3e-bc5a-4600-a347-8bd23740ecb2";
  const existingAdminId = "04bb5ee3-975a-4e5f-8937-9e8963fb11e5";
  
  // Insert an invoice to trigger sequence
  try {
    const [invoice] = await db.insert(invoices).values({
        ownerId: existingOwnerId,
        invoiceNumber: "", // Generated by database trigger
        status: "draft",
        vatableSales: "100.00",
        totalAmount: "100.00"
    }).returning();
    
    console.log("   Invoice created with generated number:", invoice.invoiceNumber);

    const [payment] = await db.insert(payments).values({
        invoiceId: invoice.id,
        receiptNumber: "", // Generated by database trigger
        amountPaid: "100.00",
        method: "cash",
        recordedBy: existingAdminId
    }).returning();
    
    console.log("   Payment created with generated receipt number:", payment.receiptNumber);

    // Clean up
    await db.delete(payments).where(eq(payments.id, payment.id));
    await db.delete(invoices).where(eq(invoices.id, invoice.id));
    console.log("   Cleanup successful");

  } catch (error) {
    console.error("   Test failed:", error);
  }
  process.exit(0);
}

verifyP41();
